# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

def shared_pods
    pod 'RxSwift', '5.1.1'
    pod 'FLEX'
    pod 'Moya/RxSwift'
end


target 'MyMVVMApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  shared_pods
  pod 'RxCocoa', '5.1.1'

  target 'MyMVVMAppTests' do
    inherit! :search_paths
	shared_pods
  end

  target 'MyMVVMAppUITests' do
  shared_pods
  end

end
